[package]
name = "DS210-Rust-Final-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.0"
petgraph = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
statrs = "0.16"
